server:
   port: 80
   servlet:
      context-path: /

spring:
#   datasource:
#      primary:
#         jdbc-url: jdbc:postgresql://localhost:5432/db_warning-monitor
#         username: root
#         password: mlog123

   jpa:
      generate-ddl: on
