server:
  port: 8080
  servlet:
    context-path: /
  max-http-header-size: 1024000

spring:
  profiles:
    active: locale

  application:
    name: springboot-jpa

  jackson:
    default-property-inclusion: ALWAYS
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

  jpa:
    show-sql: on
    generate-ddl: on
    open-in-view: on
    hibernate:
      primary-dialect: org.hibernate.dialect.PostgreSQL9Dialect
    primary:
      database: postgresql

  datasource:
    primary:
      jdbc-url: jdbc:postgresql://localhost:5432/postgres
      driver-class-name: org.postgresql.Driver
      username: root
      password: SXyjzx_123
      #验证连接的有效性
      test-while-idle: true
      #获取连接时候验证，会影响性能
      test-on-borrow: true
      validation-query: SELECT 1 FROM DUAL
      #空闲连接回收的时间间隔，与test-while-idle一起使用，设置5分钟
      time-between-eviction-runs-millis: 300000
      #连接池空闲连接的有效时间 ，设置30分钟
      min-evictable-idle-time-millis: 1800000
      maximum-pool-size: 50 # default is 10
      max-lifetime: 60000 # default is 30 minus
    #    schema:
    #      - classpath:init.sql/schema-warning.sql
    #      - classpath:init.sql/schema-channel.sql
    initialization-mode: never

  redis:
    host: 69.230.253.80
    port: 6379
    password: yiJi123!!
    database: 1
    jedis:
      pool:
        max-active: 20 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: 10 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 2 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
    timeout: 10000 # 连接超时时间（毫秒）

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  cloud:
    nacos:
      discovery:
        server-addr: 68.79.13.97:8848
        group: sxyjzx
        namespace: sxyjzx
        ip: 68.79.13.97
        port: ${server.port}
    inetutils:
      ignored-interfaces:
        - docker0
        - veth.*
        - lo
        - virbr0

management:
  endpoints:
    web:
      exposure:
        include:
          - "*"

mlog:
  oss:
    minio:
      end-point: http://69.230.253.80:9000/
      default-bucket: radar

  swagger:
    title: 系统文档 Apis
    version: 1.0-SNAPSHOT
    contact:
      name: Jack Li
      email: lishuai@mlogcn.com
