server:
   port: 8080
   servlet:
      context-path: /

spring:
   jpa:
      show-sql: off
      generate-ddl: on

   datasource:
      primary:
         jdbc-url: jdbc:postgresql://10.172.17.155:5432/db_warning-monitor
         driver-class-name: org.postgresql.Driver
         username: root
         password: SXyjzx_123
      initialization-mode: never

   redis:
      password: yiJi123!!
      cluster:
         nodes: 10.172.17.189:6379,10.172.17.164:6379,10.172.17.193:6379

   cloud:
      nacos:
         discovery:
            server-addr: 10.172.17.193:9020
            group: sxyjzx
            namespace: sxyjzx
            port: ${server.port}
            ip: null

mlog:
   oss:
      minio:
         end-point: http://10.172.17.195:9000
